[package]
name = "regular_mind"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
#simple-logging = "2.0.2"
env_logger = "0.9.0"
log4rs = "1.1.1"


serde_json = "1.0"
serde_yaml = "0.8"

[features]
log_log4rs = []
log_env_logger = []
default = ["log_env_logger"]